# Generated by Django 5.0.3 on 2024-07-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_category_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='schedule',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.TextField(null=True),
        ),
    ]
