# Generated by Django 5.0.3 on 2024-07-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='schedule',
            field=models.DateTimeField(null=True),
        ),
    ]
