# Generated by Django 5.0.3 on 2024-07-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='schedule',
            new_name='time_begin',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='time_final',
            field=models.DateTimeField(null=True),
        ),
    ]
