# Generated by Django 5.0.3 on 2024-07-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_cci'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='price',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
